"""
Five-Tier Memory System for Alfred Brain

Tier 1: Short-term Context (current session, auto-cleared)
Tier 2: Procedural Skills (learned how-to guides)
Tier 3: Episodic Memory (vector-indexed past events)
Tier 4: User Profile (dynamic mental model of Master Sam)
Tier 5: Full-Text Archive (SQLite FTS5 for all past dialogues)
"""

import json
import os
import re
import hashlib
from datetime import datetime
from pathlib import Path
from typing import Optional, List, Dict, Any, Tuple
from dataclasses import dataclass
import sqlite3

# Vector search dependencies (optional)
try:
    from sentence_transformers import SentenceTransformer
    import faiss
    from rank_bm25 import BM25Okapi
    VECTOR_SEARCH_AVAILABLE = True
except ImportError:
    SentenceTransformer = None
    faiss = None
    BM25Okapi = None
    VECTOR_SEARCH_AVAILABLE = False

import numpy as np

# Constants
OBSIDIAN_VAULT = Path(
    os.environ.get("OBSIDIAN_VAULT_PATH", r"C:\Coding\notes idk obsidian\Aflred-brain")
)
MEMORY_DIR = OBSIDIAN_VAULT / "Memory"
T2_SKILLS_DIR = MEMORY_DIR / "T2-Skills"
T3_EPISODIC_DIR = MEMORY_DIR / "T3-Episodic"
T5_ARCHIVE_DIR = MEMORY_DIR / "T5-Archive"
PROFILES_DIR = MEMORY_DIR / "T4-UserProfile"


@dataclass
class ContextItem:
    """Tier 1: Short-term context item"""

    key: str
    value: Any
    timestamp: str
    ttl: int = 3600  # seconds

    def is_expired(self) -> bool:

        created = datetime.fromisoformat(self.timestamp)
        age = (datetime.now() - created).total_seconds()
        return age > self.ttl


class FiveTierMemory:
    """
    Five-tier memory system for Hermes-style learning.
    """

    def __init__(self):
        self._t1_context: Dict[str, ContextItem] = {}
        self._t2_skills_index: List[Dict] = []
        self._t4_profile: Optional[Dict] = None
        self._t5_db: Optional[sqlite3.Connection] = None

        # T3 Vector Search (Phase 4)
        self._t3_vector_model: Optional[SentenceTransformer] = None
        self._t3_faiss_index: Optional[faiss.IndexFlatIP] = None
        self._t3_episode_embeddings: List[Dict] = []  # {path, embedding, metadata}

        self._ensure_dirs()
        self._init_t5_database()
        self._load_t2_skills_index()
        self._load_t4_profile()
        self._init_t3_vector_search()

    def _ensure_dirs(self):
        """Ensure memory directories exist."""
        for d in [T2_SKILLS_DIR, T3_EPISODIC_DIR, T5_ARCHIVE_DIR, PROFILES_DIR]:
            d.mkdir(parents=True, exist_ok=True)

        # Create T1 context placeholder if not exists
        t1_dir = MEMORY_DIR / "T1-Context"
        t1_dir.mkdir(parents=True, exist_ok=True)

    # ============ TIER 1: SHORT-TERM CONTEXT ============

    def t1_set(self, key: str, value: Any, ttl: int = 3600) -> None:
        """Store item in short-term context."""
        self._t1_context[key] = ContextItem(
            key=key, value=value, timestamp=datetime.now().isoformat(), ttl=ttl
        )

    def t1_get(self, key: str, default: Any = None) -> Any:
        """Retrieve from short-term context."""
        item = self._t1_context.get(key)
        if item and not item.is_expired():
            return item.value
        return default

    def t1_clear_expired(self) -> int:
        """Clear expired context items."""
        expired = [k for k, v in self._t1_context.items() if v.is_expired()]
        for k in expired:
            del self._t1_context[k]
        return len(expired)

    def t1_clear_all(self) -> None:
        """Clear all short-term context (session end)."""
        self._t1_context.clear()

        # Also clear T1-Context folder
        for f in (MEMORY_DIR / "T1-Context").glob("*"):
            if f.name != "README.md":
                f.unlink()

    def t1_get_all(self) -> Dict[str, Any]:
        """Get all non-expired context."""
        return {k: v.value for k, v in self._t1_context.items() if not v.is_expired()}

    # ============ TIER 2: PROCEDURAL SKILLS ============

    def t2_save_skill(self, skill_id: str, content: str, title: str) -> str:
        """Save a learned skill to T2-Skills."""
        filename = f"{title.lower().replace(' ', '-')}-{skill_id[:8]}.md"
        filepath = T2_SKILLS_DIR / filename

        # Add metadata header
        full_content = f"""# Learned Skill: {title}

**Skill ID:** `{skill_id}`
**Created:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Master Sam:** Completed successfully

---

{content}

---
*Auto-generated by Alfred Brain*
"""

        filepath.write_text(full_content, encoding="utf-8")
        self._load_t2_skills_index()
        return str(filepath)

    def t2_find_skill(self, task_description: str) -> Optional[Dict]:
        """Find relevant skill based on task description."""
        task_lower = task_description.lower()

        # Simple keyword matching (can be upgraded to vector search)
        best_match = None
        best_score = 0

        for skill in self._t2_skills_index:
            score = self._calculate_skill_match(task_lower, skill)
            if score > best_score and score > 0.3:  # threshold
                best_score = score
                best_match = skill

        return best_match

    def _calculate_skill_match(self, query: str, skill: Dict) -> float:
        """Calculate relevance score between query and skill."""
        score = 0.0

        # Check title match
        title = skill.get("title", "").lower()
        if title:
            title_words = set(title.split())
            query_words = set(query.split())
            overlap = len(title_words & query_words)
            score += overlap * 0.5

        # Check tags match
        tags = set(skill.get("tags", []))
        query_words = set(query.split())
        overlap = len(tags & query_words)
        score += overlap * 0.3

        return min(score, 1.0)

    def t2_get_skill_content(self, skill_path: str) -> Optional[str]:
        """Get full content of a skill file."""
        try:
            return Path(skill_path).read_text(encoding="utf-8")
        except Exception:
            return None

    def _load_t2_skills_index(self) -> None:
        """Load skills index for fast lookup."""
        self._t2_skills_index = []

        for f in T2_SKILLS_DIR.glob("*.md"):
            if f.name == "README.md":
                continue

            content = f.read_text(encoding="utf-8")

            # Parse skill info from content
            skill = {
                "path": str(f),
                "title": self._extract_skill_title(content),
                "skill_id": self._extract_skill_id(content),
                "tags": self._extract_tags(content),
            }
            self._t2_skills_index.append(skill)

    def _extract_skill_title(self, content: str) -> str:
        """Extract skill title from markdown."""
        for line in content.split("\n"):
            if line.startswith("# Learned Skill:"):
                return line.replace("# Learned Skill:", "").strip()
        return "Unknown Skill"

    def _extract_skill_id(self, content: str) -> str:
        """Extract skill ID from markdown."""
        for line in content.split("\n"):
            if "Skill ID:" in line:
                return line.split("`")[1] if "`" in line else ""
        return ""

    def _extract_tags(self, content: str) -> List[str]:
        """Extract tags from markdown."""
        tags = []
        in_tags_section = False
        for line in content.split("\n"):
            if line.startswith("## Tags") or line.startswith("### Tags"):
                in_tags_section = True
                continue
            if in_tags_section and line.strip().startswith("#"):
                tag = line.strip().replace("#", "").replace("-", " ").strip()
                if tag:
                    tags.append(tag.lower())
        return tags

    # ============ TIER 3: EPISODIC MEMORY ============

    def t3_find_episodes(self, query: str, max_results: int = 5) -> List[Dict]:
        """Find relevant episodes using hybrid search (vector + keyword + temporal).

        Hybrid Scoring: Final Score = (Vector_Score × 0.4) + (Keyword_Score × 0.3) + (Recency × 0.3)
        Falls back to keyword-only if vector search unavailable.
        """
        # Lazy BM25 rebuild if dirty
        if getattr(self, '_t3_bm25_dirty', False):
            self._rebuild_t3_bm25()
            self._t3_bm25_dirty = False
        if self._t3_vector_model and self._t3_faiss_index and self._t3_faiss_index.ntotal > 0:
            return self._t3_hybrid_search(query, max_results)
        else:
            return self._t3_keyword_search(query, max_results)

    def _t3_hybrid_search(self, query: str, max_results: int = 5) -> List[Dict]:
        """Hybrid search: Vector(0.4) + BM25(0.3) + Recency(0.3)."""
        results_dict = {}  # path -> result dict

        # 1. Vector search (FAISS)
        query_embedding = self._t3_vector_model.encode([query])
        faiss.normalize_L2(query_embedding)
        k = min(max_results * 2, self._t3_faiss_index.ntotal)
        vector_scores, indices = self._t3_faiss_index.search(
            query_embedding.astype(np.float32), k
        )

        for score, idx in zip(vector_scores[0], indices[0]):
            if idx < 0 or idx >= len(self._t3_episode_embeddings):
                continue
            
            episode = self._t3_episode_embeddings[idx]
            path = episode["path"]
            
            if path not in results_dict:
                results_dict[path] = {
                    "path": path,
                    "title": episode["title"],
                    "vector_score": 0.0,
                    "bm25_score": 0.0,
                    "recency": 0.0,
                    "final_score": 0.0
                }
            results_dict[path]["vector_score"] = max(results_dict[path]["vector_score"], float(score))

        # 2. BM25 search
        if self._t3_bm25:
            tokenized_query = query.lower().split()
            bm25_scores = self._t3_bm25.get_scores(tokenized_query)
            
            for i, score in enumerate(bm25_scores):
                if i < len(self._t3_episode_embeddings):
                    path = self._t3_episode_embeddings[i]["path"]
                    if path in results_dict:
                        results_dict[path]["bm25_score"] = float(score)
                    elif score > 0:
                        results_dict[path] = {
                            "path": path,
                            "title": self._t3_episode_embeddings[i]["title"],
                            "vector_score": 0.0,
                            "bm25_score": float(score),
                            "recency": 0.0,
                            "final_score": 0.0
                        }

        # 3. Calculate recency and final scores
        for path, result in results_dict.items():
            episode_path = Path(path)
            if episode_path.exists():
                days_since = self._calculate_days_since(episode_path)
                result["recency"] = 1 / (1 + days_since)
                result["days_since"] = days_since
                
                # Normalize scores — cap BM25 by max observed score across results
                max_bm25 = max((r["bm25_score"] for r in results_dict.values()), default=1.0)
                norm_bm25 = min(result["bm25_score"] / max_bm25, 1.0) if max_bm25 > 0 else 0.0
                result["final_score"] = (
                    result["vector_score"] * 0.4 +
                    norm_bm25 * 0.3 +
                    result["recency"] * 0.3
                )

        # Recency must never be the sole reason an episode surfaces -- require
        # some actual topical signal (vector or keyword) in addition to the
        # blended score. all-MiniLM-L6-v2 cosine similarity between unrelated
        # sentences typically sits below ~0.25-0.3; genuine topical matches
        # usually land well above that. Confirmed live without this: a
        # just-saved, topically unrelated episode (recency ~1.0) outscored
        # into the top results and got parroted back for a different task.
        MIN_TOPICAL_VECTOR = 0.3
        results = [
            r for r in results_dict.values()
            if r["vector_score"] >= MIN_TOPICAL_VECTOR or r["bm25_score"] > 0
        ]
        results.sort(key=lambda x: x["final_score"], reverse=True)
        return results[:max_results]

    def _t3_keyword_search(self, query: str, max_results: int = 5) -> List[Dict]:
        """Keyword-based search with temporal decay (original implementation)."""
        results = []
        query_words = query.lower().split()

        for f in T3_EPISODIC_DIR.glob("*.md"):
            if f.name == "README.md":
                continue

            try:
                content = f.read_text(encoding="utf-8").lower()
                
                if any(word in content for word in query_words):
                    similarity = sum(1 for word in query_words if word in content)
                    days_since = self._calculate_days_since(f)
                    recency = 1 / (1 + days_since)
                    final_score = (similarity * 0.6) + (recency * 0.4)

                    results.append({
                        "path": str(f),
                        "title": f.stem,
                        "vector_score": 0.0,
                        "keyword_score": similarity,
                        "similarity": similarity,
                        "recency": recency,
                        "days_since": days_since,
                        "final_score": final_score,
                    })
            except Exception:
                pass

        results.sort(key=lambda x: x["final_score"], reverse=True)
        return results[:max_results]

    def _calculate_days_since(self, file_path: Path) -> float:
        """Calculate days since file was modified."""
        mtime = datetime.fromtimestamp(file_path.stat().st_mtime)
        delta = datetime.now() - mtime
        return delta.total_seconds() / 86400

    # ============ TIER 3: VECTOR SEARCH (Phase 4) ============

    def _init_t3_vector_search(self) -> None:
        """Initialize vector search for T3 episodic memory."""
        if not VECTOR_SEARCH_AVAILABLE:
            return

        try:
            # Load lightweight model for embeddings
            model_name = "all-MiniLM-L6-v2"  # Fast, good quality
            self._t3_vector_model = SentenceTransformer(model_name)
            
            # Initialize FAISS index (Inner Product for cosine similarity)
            embedding_dim = self._t3_vector_model.get_sentence_embedding_dimension()
            self._t3_faiss_index = faiss.IndexFlatIP(embedding_dim)
            
            # Initialize BM25
            self._t3_bm25 = None
            self._t3_bm25_corpus = []
            self._t3_bm25_dirty = False

            # Load existing episodes into index
            self._rebuild_t3_vector_index()
            # Rebuild BM25 after vector index is ready
            self._rebuild_t3_bm25()
        except Exception as e:
            print(f"[Alfred] Vector search init failed: {e}")
            self._t3_vector_model = None
            self._t3_faiss_index = None

    def _rebuild_t3_vector_index(self) -> None:
        """Rebuild FAISS index and BM25 corpus from all T3 episodes."""
        if not self._t3_vector_model or not self._t3_faiss_index:
            return

        self._t3_faiss_index.reset()
        self._t3_episode_embeddings = []
        self._t3_bm25_corpus = []

        episodes = list(T3_EPISODIC_DIR.glob("*.md"))
        if not episodes:
            return

        # Batch encode all episodes
        contents = []
        tokenized_corpus = []
        
        for f in episodes:
            if f.name == "README.md":
                continue
            content = f.read_text(encoding="utf-8")
            contents.append(content[:1000])  # First 1000 chars for embedding
            self._t3_bm25_corpus.append(content)
            tokenized_corpus.append(content.lower().split())  # Simple tokenization

        if not contents:
            return

        # Generate embeddings for FAISS
        embeddings = self._t3_vector_model.encode(contents, show_progress_bar=False)
        faiss.normalize_L2(embeddings)
        self._t3_faiss_index.add(embeddings.astype(np.float32))
        
        # Build BM25 index
        if BM25Okapi:
            self._t3_bm25 = BM25Okapi(tokenized_corpus)

        # Store metadata
        idx = 0
        for f in episodes:
            if f.name == "README.md":
                continue
            self._t3_episode_embeddings.append({
                "path": str(f),
                "title": f.stem,
                "embedding_idx": idx
            })
            idx += 1

    def _rebuild_t3_bm25(self) -> None:
        """Rebuild BM25 index from all T3 episodes."""
        tokenized_corpus = []
        for f in T3_EPISODIC_DIR.glob("*.md"):
            if f.name == "README.md":
                continue
            content = f.read_text(encoding="utf-8")
            tokenized_corpus.append(content.lower().split())

        if tokenized_corpus and BM25Okapi:
            self._t3_bm25 = BM25Okapi(tokenized_corpus)

    def t3_save_episode(self, title: str, content: str, metadata: Dict = None, session_id: str = "") -> str:
        """Save an episodic memory (past event) with vector embedding."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{title[:50].replace(' ', '-')}_{timestamp}.md"
        filepath = T3_EPISODIC_DIR / filename

        meta = metadata or {}
        meta["session_id"] = session_id

        full_content = f"""# Episode: {title}

**Timestamp:** {datetime.now().isoformat()}
**Metadata:** {json.dumps(meta, indent=2)}

---

{content}

---
*Auto-generated by Alfred Brain*
"""

        filepath.write_text(full_content, encoding="utf-8")
        
        # Update vector index if available
        if self._t3_vector_model and self._t3_faiss_index:
            try:
                embedding = self._t3_vector_model.encode([content[:1000]])
                faiss.normalize_L2(embedding)
                self._t3_faiss_index.add(embedding.astype(np.float32))
                self._t3_episode_embeddings.append({
                    "path": str(filepath),
                    "title": filepath.stem,
                    "embedding_idx": self._t3_faiss_index.ntotal - 1
                })
            except Exception as e:
                print(f"[Alfred] Vector index update failed: {e}")

        # Rebuild BM25 incrementally — mark dirty for lazy rebuild
        self._t3_bm25_dirty = True
        
        return str(filepath)

    # ============ TIER 4: USER PROFILE ============

    def t4_load_profile(self, profile_name: str = "Sam") -> Dict:
        """Load user profile."""
        profile_path = PROFILES_DIR / f"{profile_name}.md"

        if profile_path.exists():
            content = profile_path.read_text(encoding="utf-8")
            return self._parse_profile_markdown(content)

        return {}

    def t4_set(self, key: str, value: Any, section: str = "Preferences") -> None:
        """Save a value to the user profile and persist to disk."""
        if not self._t4_profile:
            self._t4_profile = self.t4_load_profile()

        if section not in self._t4_profile:
            self._t4_profile[section] = {}
        self._t4_profile[section][key] = value
        self._save_t4_profile()

    def t4_get(self, key: str, default: Any = None, section: str = None) -> Any:
        """Get value from user profile."""
        if not self._t4_profile:
            self._t4_profile = self.t4_load_profile()

        if section:
            return self._t4_profile.get(section, {}).get(key, default)

        # Search all sections
        for s, data in self._t4_profile.items():
            if isinstance(data, dict) and key in data:
                return data[key]
        return default

    _T4_SEARCH_STOPWORDS = {
        "what", "do", "you", "know", "about", "have", "got", "saved",
        "tell", "me", "my", "the", "a", "an", "is", "are", "to", "for",
        "of", "on", "in", "i", "like", "please", "can", "could", "would",
        "just", "curious", "whats", "hey", "yeah", "any",
    }

    def t4_search(self, query: str) -> List[Tuple[str, Any]]:
        """Natural-language search over T4, for queries that don't match a
        stored key exactly. t4_get() is an exact-key lookup only -- a query
        like "what do you know about what I like to eat" will never equal
        the literal key "favorite_food", confirmed live (returned "No
        memories" despite the fact being present under that key).

        Three layers, cheapest first:
          1. Exact key match (delegates to t4_get).
          2. Stopword-stripped keyword overlap against keys AND values --
             catches most everyday phrasing cheaply, no model call.
          3. Semantic fallback via the same embedding model T3 already
             loads (all-MiniLM-L6-v2) -- only reached if 1-2 find nothing,
             since it's the one layer with real cost. Needed because some
             real queries share no substring with the answer at all (e.g.
             "eat" vs. key "favorite_food" / value "Biryani" -- zero
             lexical overlap, but "eat" and "food" are semantically close).

        Returns a list of (key, value) pairs, best-effort ranked.
        """
        if not self._t4_profile:
            self._t4_profile = self.t4_load_profile()

        for section, data in self._t4_profile.items():
            if isinstance(data, dict) and query in data:
                return [(query, data[query])]

        normalized = re.sub(r"[^\w\s]", " ", query.lower())
        words = {
            w for w in normalized.split()
            if w not in self._T4_SEARCH_STOPWORDS and len(w) > 2
        }

        all_pairs: List[Tuple[str, Any]] = []
        for section, data in self._t4_profile.items():
            if isinstance(data, dict):
                all_pairs.extend(data.items())

        if words:
            keyword_matches = []
            for key, val in all_pairs:
                key_norm = key.lower().replace("_", " ")
                val_str = str(val).lower()
                if any(w in key_norm or w in val_str for w in words):
                    keyword_matches.append((key, val))
            if keyword_matches:
                return keyword_matches

        if self._t3_vector_model is not None and all_pairs:
            try:
                pair_texts = [f"{k.replace('_', ' ')}: {v}" for k, v in all_pairs]
                embeddings = self._t3_vector_model.encode(
                    pair_texts + [query], show_progress_bar=False
                )
                query_vec = embeddings[-1]
                pair_vecs = embeddings[:-1]
                import numpy as np
                q_norm = query_vec / (np.linalg.norm(query_vec) + 1e-8)
                scored = []
                for (key, val), vec in zip(all_pairs, pair_vecs):
                    v_norm = vec / (np.linalg.norm(vec) + 1e-8)
                    sim = float(np.dot(q_norm, v_norm))
                    if sim >= 0.35:  # same floor used for T3 topical relevance
                        scored.append((sim, key, val))
                scored.sort(reverse=True)
                return [(k, v) for _, k, v in scored[:3]]
            except Exception:
                pass

        return []

    def t4_forget(self, key_or_query: str) -> str:
        """Delete a fact from the user profile by exact key or natural-
        language query. Mirrors the safe-resolution pattern already shipped
        for delete_event_by_query (gws_client.py) -- exact key match first,
        else fall back to t4_search's keyword/semantic resolution; refuses
        to guess when a query matches more than one distinct key rather than
        deleting all of them.
        """
        if not self._t4_profile:
            self._t4_profile = self.t4_load_profile()

        for section, data in self._t4_profile.items():
            if isinstance(data, dict) and key_or_query in data:
                value = data.pop(key_or_query)
                self._save_t4_profile()
                return f"Forgot: {key_or_query} = {value}"

        matches = self.t4_search(key_or_query)
        if not matches:
            return f"No stored fact found matching '{key_or_query}'."

        distinct_keys = {k for k, _ in matches}
        if len(distinct_keys) > 1:
            lines = [f"{len(distinct_keys)} facts match '{key_or_query}' -- say which one by exact key instead:"]
            for k, v in matches:
                lines.append(f"  - {k}: {v}")
            return "\n".join(lines)

        key = matches[0][0]
        for section, data in self._t4_profile.items():
            if isinstance(data, dict) and key in data:
                value = data.pop(key)
                self._save_t4_profile()
                return f"Forgot: {key} = {value}"
        return f"No stored fact found matching '{key_or_query}'."

    def _save_t4_profile(self) -> None:
        """Persist user profile to disk."""
        profile_path = PROFILES_DIR / "Sam.md"
        lines = ["# Sam's User Profile\n"]
        for section, data in self._t4_profile.items():
            if isinstance(data, dict) and data:
                lines.append(f"\n## {section}\n")
                for k, v in data.items():
                    lines.append(f"{k}: {v}\n")
        profile_path.write_text("".join(lines), encoding="utf-8")

    def _parse_profile_markdown(self, content: str) -> Dict:
        """Parse profile markdown into dict."""
        profile = {}
        current_section = "Preferences"
        first_line = True

        for line in content.split("\n"):
            stripped = line.strip()
            if first_line:
                first_line = False
                continue  # Skip title line
            if stripped.startswith("##"):
                current_section = stripped.lstrip("#").strip()
                if current_section not in profile:
                    profile[current_section] = {}
            elif ":" in stripped and not stripped.startswith("#"):
                key, value = stripped.split(":", 1)
                key = key.strip().lstrip("- ")
                value = value.strip()
                if current_section not in profile:
                    profile[current_section] = {}
                profile[current_section][key] = value

        return profile

    def _load_t4_profile(self) -> None:
        """Pre-load user profile."""
        self._t4_profile = self.t4_load_profile()

    # ============ TIER 5: FULL-TEXT ARCHIVE ============

    def _init_t5_database(self) -> None:
        """Initialize SQLite FTS5 database."""
        db_path = T5_ARCHIVE_DIR / "archive.db"
        self._t5_db = sqlite3.connect(str(db_path))

        # Create FTS5 table if not exists
        self._t5_db.execute("""
            CREATE VIRTUAL TABLE IF NOT EXISTS archive_fts 
            USING fts5(title, content, tokenize='porter')
        """)
        self._t5_db.commit()

    def t5_index_document(
        self, title: str, content: str, source: str = "unknown"
    ) -> None:
        """Add document to full-text archive."""
        self._t5_db.execute(
            "INSERT INTO archive_fts (rowid, title, content) VALUES (NULL, ?, ?)",
            (title, content),
        )
        self._t5_db.commit()

    def t5_search(self, query: str, max_results: int = 10) -> List[Dict]:
        """Full-text search across all archived content."""
        # Sanitize FTS5 query - only strip characters that break FTS5 syntax
        import re as _re
        sanitized = _re.sub(r'[\[\]{}^~?]', ' ', query)
        sanitized = _re.sub(r'\s+', ' ', sanitized).strip()
        if not sanitized:
            return []
        # Wrap each term as its own FTS5 quoted phrase (doubling any internal
        # double-quotes to escape them). A bare apostrophe -- e.g. "myself's",
        # "user's" -- is not itself in the stripped character class above, but
        # FTS5's own query-syntax parser (not just SQL string parsing, which
        # the "?" binding already protects against) throws "syntax error near
        # '\''" on an unquoted term containing one. Quoting each term forces
        # FTS5 to treat it as a literal phrase instead of parsing it as query
        # syntax, which sidesteps the crash while preserving the original
        # implicit-AND-across-terms, order-independent matching. Confirmed
        # live: "Send a test email to myself with subject 'Phase 1 Test'..."
        # crashed memory_search before this fix.
        terms = [t for t in sanitized.split(' ') if t]
        fts_query = ' '.join('"' + t.replace('"', '""') + '"' for t in terms)
        cursor = self._t5_db.execute(
            "SELECT rowid, title, snippet(archive_fts, 1, '<mark>', '</mark>', '...', 32) "
            "FROM archive_fts WHERE archive_fts MATCH ? LIMIT ?",
            (fts_query, max_results),
        )

        results = []
        for row in cursor:
            results.append({"rowid": row[0], "title": row[1], "snippet": row[2]})

        return results

    def t5_archive_conversation(self, conversation: List[Dict]) -> None:
        """Archive a conversation for future retrieval."""
        content = "\n".join(
            [
                f"{msg.get('role', 'unknown')}: {msg.get('content', '')}"
                for msg in conversation
            ]
        )

        self.t5_index_document(
            title=f"Conversation {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            content=content,
            source="conversation",
        )

    def t5_append(self, content: str, title: str = None) -> None:
        """Append content to T5 archive as a new markdown file."""
        from datetime import datetime
        
        if title is None:
            title = f"Task {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        
        # Use conversation archive format
        self.t5_index_document(
            title=title,
            content=content,
            source="thinking_trace",
        )

    # ============ UTILITY METHODS ============

    def get_context_for_llm(self, query: str = None) -> str:
        """Get formatted context for LLM prompts with optional T3 episodic memory."""
        lines = ["[MEMORY CONTEXT]"]

        # T1: Short-term
        t1 = self.t1_get_all()
        if t1:
            lines.append("\n## Current Session Context:")
            for k, v in t1.items():
                lines.append(f"- {k}: {v}")

        # T3: Episodic Memory (if query provided)
        if query:
            t3_results = self.t3_find_episodes(query, max_results=3)
            if t3_results:
                lines.append("\n## Relevant Past Episodes:")
                for r in t3_results:
                    try:
                        content = Path(r["path"]).read_text(encoding="utf-8")[:500]
                        lines.append(f"\n### {r['title']} (score: {r['final_score']:.2f})")
                        lines.append(content)
                    except Exception:
                        pass

        # T4: User Profile — organized by section for LLM readability
        if self._t4_profile:
            lines.append("\n## User Profile:")
            for section, data in self._t4_profile.items():
                if isinstance(data, dict) and data:
                    lines.append(f"\n### {section}")
                    for k, v in data.items():
                        lines.append(f"- {k}: {v}")

        return "\n".join(lines)

    def generate_skill_id(self) -> str:
        """Generate unique skill ID."""
        return hashlib.md5(datetime.now().isoformat().encode()).hexdigest()[:12]


# Singleton instance
_memory_instance: Optional[FiveTierMemory] = None


def get_memory() -> FiveTierMemory:
    """Get singleton memory instance."""
    global _memory_instance
    if _memory_instance is None:
        _memory_instance = FiveTierMemory()
    return _memory_instance
