"""
Skill Manager for Alfred-style autonomous skill generation.

Handles:
- Skill creation from complex tasks
- Skill self-improvement when errors occur
- Skill retrieval and matching
- Ecosystem search: falls back to skills.sh when local skills don't match
"""

import hashlib
import json
import math
import re as _re
import subprocess
import time
from datetime import datetime
from pathlib import Path
from typing import Optional, List, Dict, Any
from dataclasses import dataclass

from .five_tier import get_memory, T2_SKILLS_DIR

VALID_TOOLS: set = {
    "chat", "calculator", "calendar", "email", "web_search", "web_fetch",
    "shell", "read_file", "write_file", "list_directory", "glob",
    "screenshot", "gws", "open_app", "time", "remember",
    "set_reminder", "list_reminders", "delete_reminder",
    "memory_save", "memory_search", "weather", "run_code",
}

STOP_WORDS: set = {
    "the", "a", "an", "is", "are", "do", "my", "for", "to",
    "of", "in", "on", "at", "with", "and", "or", "but", "it",
    "that", "this", "check", "run", "get", "please", "can",
    "how", "what", "find", "use", "will", "all", "be", "by",
    "from", "has", "have", "not", "we", "you", "your", "does",
}


@dataclass
class Skill:
    skill_id: str
    title: str
    description: str
    steps: List[Dict[str, str]]
    tags: List[str]
    complexity: str
    success_count: int = 0
    failure_count: int = 0
    path: str = ""

    def to_markdown(self) -> str:
        steps_md = "\n\n".join(
            [
                f"### Step {i + 1}: {step.get('description', 'Unknown')}\n"
                f"- **Tool:** `{step.get('tool')}`\n"
                f"- **Params:** `{step.get('params', '{}')}`"
                for i, step in enumerate(self.steps)
            ]
        )

        total = self.success_count + self.failure_count
        rate = f"{self.success_count}/{total}" if total else "No data"

        return f"""# Learned Skill: {self.title}

**Skill ID:** `{self.skill_id}`
**Created:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Complexity:** {self.complexity}
**Success Rate:** {rate}

---

## Description
{self.description}

## Steps
{steps_md}

## Tags
{', '.join([f'#{t}' for t in self.tags])}

---
*Auto-generated by Alfred Brain*
"""

    @classmethod
    def from_markdown(cls, path: str, content: str) -> "Skill":
        lines = content.split("\n")
        skill_id = ""
        title = ""
        description = ""
        complexity = "moderate"
        tags = []
        steps = []

        for i, line in enumerate(lines):
            if "Skill ID:" in line:
                parts = line.split("`")
                if len(parts) > 1:
                    skill_id = parts[1]
            elif "Learned Skill:" in line:
                title = line.replace("# Learned Skill:", "").replace("# Learned Skill:", "").strip()
            elif line.strip() == "## Description" and i + 1 < len(lines):
                description = lines[i + 1].strip().strip('"').strip("'")
            elif "Complexity:" in line:
                parts = line.split("**Complexity:**")
                if len(parts) > 1:
                    complexity = parts[1].strip()

        current_step = {}
        for line in lines:
            if line.startswith("### Step") or "Step" in line:
                if current_step and "tool" in current_step:
                    steps.append(current_step)
                current_step = {}
                if ":" in line:
                    current_step["description"] = line.split(":", 1)[1].strip()
            elif "**Tool:**" in line or "Tool:" in line:
                parts = line.split("`")
                if len(parts) > 1:
                    current_step["tool"] = parts[1]
                elif ":" in line:
                    current_step["tool"] = line.split(":", 1)[1].strip()
            elif "**Params:**" in line or "Params:" in line:
                params = line.split("`")[1] if "`" in line else "{}"
                current_step["params"] = params

        if current_step:
            steps.append(current_step)

        return cls(
            skill_id=skill_id,
            title=title,
            description=description,
            steps=steps,
            tags=tags,
            complexity=complexity,
            path=path,
        )


class SkillManager:
    ECOSYSTEM_THROTTLE_SECS = 60

    def __init__(self):
        self.memory = get_memory()
        self._skills_cache: Dict[str, Skill] = {}
        self._ecosystem_cache: Dict[str, tuple] = {}
        self._load_skills_metadata()

    def _load_skills_metadata(self):
        self._skills_cache = {}
        for f in sorted(T2_SKILLS_DIR.glob("*.md")):
            if f.name == "README.md":
                continue
            try:
                content = f.read_text(encoding="utf-8")
                skill = Skill.from_markdown(str(f), content)
                if self._is_low_quality_skill(skill):
                    continue
                self._skills_cache[skill.skill_id] = skill
            except Exception as e:
                print(f"Error loading skill {f}: {e}")

    def _embed_text(self, text: str) -> Optional[List[float]]:
        try:
            if self.memory._t3_vector_model is None:
                return None
            return self.memory._t3_vector_model.encode(text).tolist()
        except Exception:
            return None

    # ─── skills.sh ecosystem integration ────────────────────────────────

    SKILLS_SH_INSTALL_DIRS = [
        Path.home() / ".agents" / "skills",
        Path.home() / ".config" / "opencode" / "skills",
    ]

    @staticmethod
    def _strip_ansi(text: str) -> str:
        return _re.compile(r'\x1b\[[0-9;]*[mK]').sub('', text)

    def _discover_skills_sh_skill_path(self, skill_name: str) -> Optional[Path]:
        for base in self.SKILLS_SH_INSTALL_DIRS:
            candidate = base / skill_name / "SKILL.md"
            if candidate.exists():
                return candidate
        return None

    def _parse_npx_find_output(self, output: str) -> List[Dict]:
        clean = self._strip_ansi(output)
        results = []
        for line in clean.split("\n"):
            line = line.strip()
            m = _re.match(r'^([\w.-]+/[\w.-]+)@([\w.-]+)', line)
            if m:
                repo = m.group(1)
                skill = m.group(2)
                installs = 0
                im = _re.search(r'([\d.]+[KMB]?)\s*installs?', line)
                if im:
                    raw = im.group(1)
                    multiplier = 1
                    if raw.endswith('K'):
                        multiplier = 1000
                        raw = raw[:-1]
                    elif raw.endswith('M'):
                        multiplier = 1000000
                        raw = raw[:-1]
                    try:
                        installs = int(float(raw.replace(',', '')) * multiplier)
                    except ValueError:
                        pass
                results.append({
                    "repo": repo,
                    "skill": skill,
                    "installs": installs,
                    "url": f"https://skills.sh/{repo}/{skill}",
                })
        return results

    def _search_skills_sh(self, query: str, max_results: int = 5) -> List[Dict]:
        now = time.time()
        cache_key = f"{query}:{max_results}"
        if cache_key in self._ecosystem_cache:
            cached_results, cached_at = self._ecosystem_cache[cache_key]
            if now - cached_at < self.ECOSYSTEM_THROTTLE_SECS:
                return cached_results
        try:
            result = subprocess.run(
                ["npx", "skills", "find", query],
                capture_output=True, text=True, timeout=30,
                env={**dict(subprocess.os.environ),
                     "NO_COLOR": "1", "FORCE_COLOR": "0"},
            )
            if result.returncode != 0:
                print(f"[SkillManager] skills find exited {result.returncode}: {result.stderr[:200]}")
                return []
            results = self._parse_npx_find_output(result.stdout)
            results.sort(key=lambda r: r["installs"], reverse=True)
            results = results[:max_results]
            self._ecosystem_cache[cache_key] = (results, now)
            return results
        except FileNotFoundError:
            print("[SkillManager] npx not found — cannot search skills.sh")
            return []
        except subprocess.TimeoutExpired:
            print("[SkillManager] skills.sh search timed out")
            return []
        except Exception as e:
            print(f"[SkillManager] skills.sh search error: {e}")
            return []

    @staticmethod
    def _parse_params(raw: Any) -> dict:
        if isinstance(raw, dict):
            return raw
        if not isinstance(raw, str) or not raw.strip():
            return {}
        try:
            return json.loads(raw)
        except (json.JSONDecodeError, TypeError):
            pass
        try:
            import ast
            parsed = ast.literal_eval(raw)
            if isinstance(parsed, dict):
                return parsed
        except Exception:
            pass
        return {}

    def _is_low_quality_skill(self, skill: Skill) -> bool:
        if not skill.steps:
            return True
        if not skill.title.strip():
            return True

        text_for_test_check = f"{skill.title} {skill.description} {' '.join(skill.tags)}".lower()
        is_zero_rate = skill.success_count == 0 and skill.failure_count == 0
        if is_zero_rate and any(w in text_for_test_check for w in {"test", "testing", "test-skill", "tools-test", "installed-skill"}):
            return True

        has_non_chat_step = False
        for s in skill.steps:
            tool = s.get("tool", "")
            if tool not in VALID_TOOLS:
                return True
            if tool != "chat":
                has_non_chat_step = True

        return not has_non_chat_step

    def _convert_skill_md_to_t2(self, md_path: Path) -> Optional[Skill]:
        content = md_path.read_text(encoding="utf-8")
        lines = content.split("\n")
        frontmatter = {}
        body_lines = []
        in_fm = False
        fm_lines = []
        for i, line in enumerate(lines):
            if i == 0 and line.strip() == "---":
                in_fm = True
                continue
            if in_fm:
                if line.strip() == "---":
                    in_fm = False
                    continue
                fm_lines.append(line)
            else:
                body_lines.append(line)
        for line in fm_lines:
            m = _re.match(r"^(\w+):\s*(.+)$", line)
            if m:
                frontmatter[m.group(1).strip()] = m.group(2).strip()
        name = frontmatter.get("name", md_path.parent.name)
        desc = frontmatter.get("description", f"Imported from skills.sh: {name}")
        body = "\n".join(body_lines).strip()

        tool_patterns = [
            _re.compile(r'(?:Tool|tool):\s*`?(\w+)`?'),
            _re.compile(r'(?:use|Use|using|Using)\s+(?:the\s+)?`?(\w+)`?\s+(?:tool|command|api)?'),
            _re.compile(r'`(\w+)`\s+(?:to|command|api)'),
        ]
        tools = set()
        for pat in tool_patterns:
            for m in pat.finditer(body):
                t = m.group(1).lower().strip()
                if t in VALID_TOOLS:
                    tools.add(t)

        if not tools:
            tools.add("chat")

        steps = []
        for tool in tools:
            steps.append({
                "tool": tool,
                "description": f"Execute step using {tool}",
                "params": {},
            })

        skill_id = hashlib.md5(
            f"{name}{datetime.now().isoformat()}".encode()
        ).hexdigest()[:12]
        words = [w for w in f"{name} {desc}".lower().split()
                 if w not in STOP_WORDS and len(w) > 2]
        tags = list(set(words))[:5]

        skill = Skill(
            skill_id=skill_id,
            title=name,
            description=desc,
            steps=steps,
            tags=tags,
            complexity="moderate",
            path="",
        )

        if self._is_low_quality_skill(skill):
            print(f"[SkillManager] Rejected low-quality skill: {name}", flush=True)
            return None

        safe_name = _re.sub(r'[^a-zA-Z0-9 ]', '', name).strip().replace(' ', '-')[:60]
        filename = f"{safe_name}-{skill_id}.md"
        out_path = T2_SKILLS_DIR / filename
        t2_content = skill.to_markdown() + f"\n*Imported from skills.sh: {name}*\n"
        out_path.write_text(t2_content, encoding="utf-8")
        skill.path = str(out_path)
        self._skills_cache[skill.skill_id] = skill
        return skill

    def _install_from_skills_sh(self, repo: str, skill_name: str) -> Optional[Skill]:
        try:
            subprocess.run(
                ["npx", "skills", "add", repo, "-s", skill_name, "-y", "-g"],
                capture_output=True, text=True, timeout=60,
            )
            md_path = self._discover_skills_sh_skill_path(skill_name)
            if md_path:
                skill = self._convert_skill_md_to_t2(md_path)
                if skill:
                    self._skills_cache[skill.skill_id] = skill
                    return skill
            return None
        except Exception as e:
            print(f"[SkillManager] skills.sh install error: {e}")
            return None

    def find_skill(self, task_description: str, search_ecosystem: bool = True) -> Optional[Skill]:
        try:
            task_emb = self._embed_text(task_description)
            if task_emb is not None:
                skills = list(self._skills_cache.values())
                if skills:
                    title_texts = [s.title for s in skills]
                    model = self.memory._t3_vector_model
                    title_embs = model.encode(title_texts).tolist()

                    norm_task = math.sqrt(sum(x * x for x in task_emb))
                    if norm_task > 0:
                        best_idx = -1
                        best_sim = 0.0
                        for i, title_emb in enumerate(title_embs):
                            dot = sum(a * b for a, b in zip(task_emb, title_emb))
                            norm_title = math.sqrt(sum(b * b for b in title_emb))
                            if norm_title > 0:
                                sim = dot / (norm_task * norm_title)
                                if sim > best_sim:
                                    best_sim = sim
                                    best_idx = i

                        if best_sim > 0.5:
                            return skills[best_idx]
        except Exception:
            pass

        task_lower = task_description.lower()
        task_words = set(task_lower.split())

        best_match = None
        best_score = 0

        for skill in self._skills_cache.values():
            title_lower = skill.title.lower()
            title_words = set(title_lower.split())

            if not title_words:
                continue

            common = task_words & title_words
            common -= STOP_WORDS

            if not common:
                continue

            title_coverage = len(common) / max(len(title_words - STOP_WORDS), 1)
            task_coverage = len(common) / max(len(task_words - STOP_WORDS), 1)
            score = (title_coverage + task_coverage) / 2

            if score > best_score and score >= 0.6:
                best_score = score
                best_match = skill

        if not best_match and search_ecosystem:
            print(f"[SkillManager] No local match — searching skills.sh for '{task_lower[:60]}...'")
            candidates = self._search_skills_sh(task_lower)
            if candidates:
                best = candidates[0]
                print(f"[SkillManager] Found: {best['repo']}@{best['skill']} ({best['installs']} installs)")
                installed = self._install_from_skills_sh(best["repo"], best["skill"])
                if installed:
                    for skill in self._skills_cache.values():
                        title_lower = skill.title.lower()
                        title_words = set(title_lower.split())
                        if not title_words:
                            continue
                        common = task_words & title_words
                        common -= STOP_WORDS
                        if not common:
                            continue
                        title_coverage = len(common) / max(len(title_words - STOP_WORDS), 1)
                        task_coverage = len(common) / max(len(task_words - STOP_WORDS), 1)
                        score = (title_coverage + task_coverage) / 2
                        if score > best_score and score >= 0.6:
                            best_score = score
                            best_match = skill

        return best_match

    def generate_skill(
        self, task: str, steps: List[Dict], task_complexity: str, had_error: bool
    ) -> Optional[Skill]:
        try:
            skill_id = hashlib.md5(
                f"{task}{datetime.now().isoformat()}".encode()
            ).hexdigest()[:12]

            title = task[:50].strip()
            if not title:
                title = f"Task {skill_id}"

            stop_words = {"the", "a", "an", "is", "are", "do", "my", "for", "to", "of", "in", "on", "at", "with", "and", "or", "but", "it", "that", "this", "check", "run", "get", "please", "can", "how", "what", "find"}
            words = [w for w in task.lower().split() if w not in stop_words and len(w) > 2]
            tags = list(set(words))[:5]

            skill = Skill(
                skill_id=skill_id,
                title=title,
                description=f"Auto-generated skill for: {task}",
                steps=steps,
                tags=tags,
                complexity=task_complexity,
                success_count=1 if not had_error else 0,
                failure_count=1 if had_error else 0,
            )

            if self._is_low_quality_skill(skill):
                print(f"[SkillManager] Rejected low-quality auto-skill: {title}", flush=True)
                return None

            safe_title = _re.sub(r'[^a-zA-Z0-9 ]', '', title).strip().replace(' ', '-')
            filename = f"{safe_title}-{skill_id}.md"
            filepath = T2_SKILLS_DIR / filename
            content = skill.to_markdown()
            filepath.write_text(content, encoding="utf-8")
            skill.path = str(filepath)

            self._skills_cache[skill_id] = skill

            return skill

        except Exception as e:
            print(f"[SkillManager] Failed to generate skill: {e}")
            return None

    def improve_skill(
        self, skill_id: str, improvement_note: str, new_steps: List[Dict] = None
    ) -> bool:
        skill = self._skills_cache.get(skill_id)
        if not skill:
            return False

        improvement_section = f"""

## Skill Improvement Log
**Updated:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Note:** {improvement_note}
"""
        if new_steps:
            improvement_section += "\n### Updated Steps:\n"
            for step in new_steps:
                improvement_section += f"- {step}\n"

        updated_content = skill.to_markdown() + improvement_section
        Path(skill.path).write_text(updated_content, encoding="utf-8")
        return True

    def get_all_skills(self) -> List[Skill]:
        return list(self._skills_cache.values())

    def get_skill_index(self) -> str:
        skills = self.get_all_skills()
        if not skills:
            return "No skills learned yet."

        lines = ["# Skill Index\n"]
        for skill in skills:
            lines.append(f"- **{skill.title}** (ID: `{skill.skill_id}`)")
            lines.append(f"  - Complexity: {skill.complexity}")
            lines.append(f"  - Success: {skill.success_count}/{skill.success_count + skill.failure_count}")
            lines.append("")

        return "\n".join(lines)


_skill_manager_instance: Optional[SkillManager] = None


def get_skill_manager() -> SkillManager:
    global _skill_manager_instance
    if _skill_manager_instance is None:
        _skill_manager_instance = SkillManager()
    return _skill_manager_instance
